// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migImageurl2addedtoabout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migImageurl2addedtoabout));
        
        string IMigrationMetadata.Id
        {
            get { return "202412220731006_mig-Imageurl2-added-to-about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
