// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migyumadmintable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migyumadmintable));
        
        string IMigrationMetadata.Id
        {
            get { return "202412251816149_mig-yumadmin-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
