// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class about_ımagefile_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(about_ımagefile_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202501051938507_about_ımagefile_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
