// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class feature_imagefile_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feature_imagefile_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202501011939180_feature_imagefile_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
